### ISSUE TITLE
solvePnP with ePnP flag

### ISSUE THREAD

**Issue by kirenebre** [kyamagu/mexopencv#149]
I am trying to evaluate ePnP performance and receive the following error when running solvePnP with the ePnP flag.  I suspect I am not sending the correct data to the function.  However, the input works fine for the iterative (default) version of solvePnP.  Any suggestions would be helpful.

Code:
Apnp =  [[8.5,  0,   0]
      [0,   8.5,  0]
      [0,    0,   1]];
dist_coef = zeros(4,1);
modelPoints = [0 0 0; 0.41 45.80 0; 45.26 0.04 0; 45.61 45.95 0];
imagePoints = [-1.2094 1.9775; -1.1058 2.4848; -0.7222 1.8587; -0.6125 2.3564];

[rvec,tvec] = cv.solvePnP(modelPoints,  imagePoints, Apnp, dist_coef', 'Flags', 'EPnP');

This call returns the following error:
Error using cv.solvePnP
Unexpected Standard exception from MEX file.
What() is:..\..\..\..\opencv\modules\imgproc\src\undistort.cpp:279: error: (-215)
CV_IS_MAT(_src) && CV_IS_MAT(_dst) && (_src->rows == 1 || _src->cols == 1) &&
(_dst->rows == 1 || _dst->cols == 1) && _src->cols + _src->rows - 1 == _dst->rows +
_dst->cols - 1 && (CV_MAT_TYPE(_src->type) == CV_32FC2 || CV_MAT_TYPE(_src->type) ==
CV_64FC2) && (CV_MAT_TYPE(_dst->type) == CV_32FC2 || CV_MAT_TYPE(_dst->type) ==
CV_64FC2) in function cvUndistortPoints

**Comment by amroamroamro** [comment]
@kirenebre 
I think I know what the problem is.. Can you try adding the following code just before the `solvePnP` call:

```MATLAB
modelPoints = permute(modelPoints,[1 3 2]);
imagePoints = permute(imagePoints,[1 3 2]);
```

Basically it formats the input points as Nx1x3/Nx1x2 matrices instead of Nx3/Nx2 for model/image points.

**Comment by kirenebre** [comment]
Using permute on the image and model points has fixed the problem.   Thank you very much.

**Comment by amroamroamro** [comment]
Great!

By the way an alternative to specify points is to use cell arrays, those get converted into `std::vector<cv::PointX_<T>>` on the C++ side, instead of a `cv::Mat`.

Note that many functions in [`calib3d`](http://docs.opencv.org/modules/calib3d/doc/camera_calibration_and_3d_reconstruction.html#solvepnp) accept points as either a contiguous matrix or a vector of points.

So in your example, you could also write:

```MATLAB
modelPoints = num2cell(modelPoints,2);    % a cell-array of 3-d points
imagePoints = num2cell(imagePoints,2);    % a cell-array of 2-d points
[rvec,tvec] = cv.solvePnP(...);
```

**Comment by drewm1980** [comment]
I also ran into this issue while calling solvePnP from python. The error is thrown inside of an undistortion function, that should not getting called at all if distortion coefficients are all zero... the poor p3p solver doesn't even get a chance to run because of misbehaving glue code. Either undistortPoints needs to be fixed to accept distCoeffs the way it is passed, or it the check should happen before solvepnp.cpp:105.

**Comment by amroamroamro** [comment]
@drewm1980 
It is explicitly mentioned in the python **notes** section of [`solvePnP` docs](https://docs.opencv.org/3.3.0/d9/d0c/group__calib3d.html#ga549c2075fac14829ff4a58bc931c033d).
It requires *image points* to be a multi-channeled array of shape (N,1,2).

In mexopencv, we do the necessary reshaping, so we accept inputs as either Nx2 / Nx1x2 (numeric array) or a vector of 2d points (cell array):
- `solvePnP`: https://github.com/kyamagu/mexopencv/blob/master/src/%2Bcv/solvePnP.cpp#L64-L66
- `undistortPoints`: https://github.com/kyamagu/mexopencv/blob/master/src/%2Bcv/undistortPoints.cpp#L44-L47

For the Python interface, this should be reported to [OpenCV](https://github.com/opencv/opencv) not here.
FYI, a quick search confirms the problem:
- https://stackoverflow.com/questions/46534126/solvepnp-object-points-image-points-shape
- http://answers.opencv.org/question/1073/what-format-does-cv2solvepnp-use-for-points-in-python/
