### ISSUE TITLE
Deploying standalone application with mex files

### ISSUE THREAD

**Issue by sbowman487** [kyamagu/mexopencv#155]
I'm trying to use MATLAB's deploy standalone application feature with an application that uses mex files.  When I try to run the program on another computer without MATLAB it is unable to read the mex files and preform the mex functions.  Any idea what I'm doing wrong or if what I'm trying isn't possible.  Thanks

**Comment by amroamroamro** [comment]
@sbowman487:

I haven't done this myself, but I imagine you need to add both the MEX-files as well as the OpenCV libraries (.dll/.so/.dylib files depending on your platform) as dependencies for the standalone application. MATLAB won't automatically discover the latter as dependencies.

Another option is to statically compile the MEX-functions against OpenCV (that way there are no deps other than the MEX-files themselves). However you're gonna have to compile them yourself, since `mexopencv.make` only handles the dynamic-linking case...

**Comment by bellz867** [comment]
I am using Ubuntu 14.0.2, opencv-2.4.9, and Matlab 2015a. I am not using mexopencv.make but instead calling make in the main directory with the Makefile. I added the shared objects directories to my library path in my bashrc so I think they should be linked. Most of the functions work just fine. It is just the functions in the private folder that are causing problems. I cannot seem to add them to my path in Matlab. 


     On Tuesday, May 26, 2015 9:58 AM, Amro <notifications@github.com> wrote:
   

 @sbowman487:I haven't done this myself, but I imagine you need to add both the MEX-files as well as the OpenCV libraries (.dll/.so/.dylib files depending on your platform) as dependencies for the standalone application. MATLAB won't automatically discover the latter as dependencies.Another option is to statically compile the MEX-functions against OpenCV (that way there are no deps other than the MEX-files themselves). However you're gonna have to compile them yourself, since mexopencv.make only handles the dynamic-linking case...—

**Comment by amroamroamro** [comment]
@bellz867: you're replying to the wrong thread!

**Comment by sbowman487** [comment]
@bellz867 : Not sure what compiler you're using but I had complications with different versions.  I had success with MATLAB R2014a, OpenCV 2.4.10 and Visual Studio Community 2013..maybe try that combo.

@amroamroamro : The only way I've gotten it to work so far is by installing EVERYTHING (MATLAB, OpenCV, MEX-files, Visual Studio, and my 'standalone') on each new machine, and compiling the MEX-functions through MATLAB before running my standalone.  So I've to two questions now:  If I statically compile the MEX-functions myself would I still need to have Visual Studio or similar installed on the new machine?  Second, how would I go about compiling the MEX-functions without using mexopencv.make?  Thanks.

**Comment by amroamroamro** [comment]
You probably didn't need to install all of that on each machine :)

Once you deploy your MATLAB code into a Windows standalone application, the requirements are as follows:

- MATLAB MCR (which is available to [download](http://www.mathworks.com/products/compiler/mcr/) for free). You don't need to install MATLAB on the target machine, just the MCR runtime. The MCR version must match the MATLAB one you used to build the deployed app.

- If you have compiled MEX-functions (which is the case with mexopencv), you must have the Visual C++ runtime also installed on the target machine. If you used VS2013 to compile the MEX-files, [here is the package](https://www.microsoft.com/en-us/download/details.aspx?id=40784) that must be installed on the target machine.

- The OpenCV dlls (`opencv_core*.dll`, `opencv_imgproc*.dll`, etc...). Either you set these as dependencies in the MATLAB Compiler project, or you manually copy them to the target machine. They *somehow* have to be made available on the `PATH` environment variable.

---

Regarding static-linking against OpenCV: if you downloaded the pre-compiled binaries, you can find two folders in the `build\x64\vc12` folder. One called `lib` the other `staticlib`, that's the one you want to link against... In this case, the requirements are same as above except for the last point, since you no longer need the OpenCV DLLs.

**Comment by RoyiAvital** [comment]
Is there a simple way to make MexOpenCV to use Static Linking of OpenCV?
I want my compilation of MexOpenCV to be independent of OpenCV.

**Comment by RoyiAvital** [comment]
Anyone could assist with a way to compile MexOpoenCV with static linking of OpenCV?

**Comment by amroamroamro** [comment]
@RoyiAvital 
Is it possible? yes

Is it simple? I don't know, never tried it :)

mexopencv officially only supports dynamic linking against OpenCV. You can statically link against it, but you have to modify the build scripts yourself (`Makefile`, `make.m`).

You'd have to build opencv manually to produce static libraries. Then you'd modify `make.m` to link against those static libs instead (`staticlib\*.lib` as mentioned above). If you're using `pkg-config` on UNIX, you'd want to call `pkg-config --static --libs opencv` in the makefile.

A word of caution; mexopencv exposes each OpenCV function/class in separate MEX-files (last time I check, we had over 400 mex-file). With dynamic linking, the size of each is quite small, and the memory overhead is negligible. However with static linking, each MEX-file gets its own embedded non-sharable copy of opencv libs. I imagine that would make the compiled mex-files considerably larger and would consume much more memory...

If you compare that to say the official python wrappers of opencv, they can get away with static linking because they produce a single binary module (.pyd file), as opposed to one per function..

**Comment by RoyiAvital** [comment]
@amroamroamro ,
Could you guide me what should I change inside `make.m` in order to change the path to the lib files?
