### ISSUE TITLE
findCirclesGrid not working

### ISSUE THREAD

**Issue by ricardojdferreira** [kyamagu/mexopencv#179]
The function is throwing an error to the console, when I try to detect circles in a circular calibration pattern.

I'm using the following code:
```
im = cv.imread('example.tif');
im2 = cv.cvtColor(im,'RGB2GRAY');
centers = cv.findCirclesGrid(im2, [15 20])
```

Error:
```
Error using cv.findCirclesGrid
Unexpected Standard exception from MEX file.
What()
is:C:\buildslave64\win64_amdocl\master_PackSlave-win64-vc11-shared\opencv\modules\core\src\copy.cpp:281:
error: (-215) channels() == CV_MAT_CN(dtype) in function cv::Mat::copyTo
```

**Comment by amroamroamro** [comment]
I made some changes to the function, and it is working fine... But before I create a pull request, can you make sure that your input image is indeed 8-bit (i.e `class(im)` is `uint8`)?

**Comment by amroamroamro** [comment]
@ricardojdferreira 
With the above changes [merged](https://github.com/kyamagu/mexopencv/pull/180) into `v3.0` branch, try the following example:

``` matlab
img = imread(fullfile(mexopencv.root(),'test','acircles_pattern.png'));

sz = [4 11];
[centers,found] = cv.findCirclesGrid(img, sz, 'SymmetricGrid',false, ...
    'BlobDetector',{'SimpleBlobDetector', 'MaxArea',1e5});

out = repmat(img,[1 1 3]);
out = cv.drawChessboardCorners(out, sz, centers, 'PatternWasFound',found);
imshow(out)
```
Here is the output with detected grid:

![out](https://cloud.githubusercontent.com/assets/83908/8888732/869ec8ae-32c2-11e5-8aef-c51f093d9503.jpg)

**Comment by ricardojdferreira** [comment]
Thanks a lot @amroamroamro !

I'll try it and give some feedback!

**Comment by amroamroamro** [comment]
@ricardojdferreira 
For now, the changes are in the `v3.0` branch, but they will soon be merged in master at some point.

For your problem above, the only change that really matters is explicit casting the image to `uint8`, so you could add a call to `im2uint8` in your code if you don't want to wait :)

In the example I gave, I had to specify non-default parameters for the blob detector because the pattern image was high-res with circles that are larger than the default threshold. I could have also resized the image in half to get around that... The idea came from [here](http://answers.opencv.org/question/3471/findcirclesgrid-not-working/).

**Comment by ricardojdferreira** [comment]
@amroamroamro thank you! It's working properly!
