### ISSUE TITLE
Modifying OPENCV files

### ISSUE THREAD

**Issue by alisher1722** [kyamagu/mexopencv#187]
Hi, I did some modifications on "brief.cpp" in order to use it in my project (I changed parameters as follow: `PATCH_SIZE=32, KERNEL_SIZE=3`)

Then, I have built it, and then when I start MATLAB and type

```
>> img=imread('cameraman.tif');
>> detector=cv.FeatureDetector('ORB');
>> keyp=detector.detect(img);
>> extract=cv.DescriptorExtractor('BriefDescriptorExtractor');
>> result1=extract.compute(img,keyp);
```

there is no differences occur.

What I have to do exactly? Should I change `brief.cpp` only, or I have to change `BriefDescriptorExtractor.cpp` too? 

And I am not sure about if MATLAB recognizes that changes or not. 

Can anybody help me, thanks

**Comment by amroamroamro** [comment]
If you've modified OpenCV source code, you have to rebuild it (at the least the affected module which is `xfeatures2d` in your case). C++ is a compiled language, not interpreted!

Assuming you didn't break any ABI compatibility, you could probably just replace the affected DLL with the new version (that would be the OpenCV DLLs you placed on you system PATH), otherwise you have to recompile meoxpencv as well against this new version.

For a simple change as you described, you don't need to modify anything in mexopencv code..
