### ISSUE TITLE
BackgoundSubtractorMOG2 sometimes return wrong mask

### ISSUE THREAD

**Issue by mehdisalehi** [kyamagu/mexopencv#205]
MOG2 is returns complete foreground mask some times. Sometimes it return proper mask for few frames and then wrong mask (All ones) in next frame than it repeats the cycle. Sometimes it works completely fine. There is no problem while using MOG. 
i am using MATLAB 2015a in 64 bit system

**Comment by kyamagu** [comment]
@mehdisalehi We can resolve an issue related to mexopencv, but your problem seems to be related to OpenCV itself or your data. I would first suggest you use C++ to do the same task, and if the problem goes away we will look into the problem. Otherwise I would suggest you report an issue in the official OpenCV forum.

**Comment by mehdisalehi** [comment]
I have test the c++ implementation and its working perfectly fine.

**Comment by amroamroamro** [comment]
@mehdisalehi I doubt it's a bug on our side. mexopencv is only a wrapper for existing OpenCV functions, with necessary conversions between MATLAB and OpenCV types...

Could you show your code (both C++ and MATLAB), preferably a minimal example we can run to reproduce the issue.

**Comment by mehdisalehi** [comment]
I have tested on another PC and its working perfectly fine there. I dont know y??? every thing is same OpenCV library same mex library.
