### ISSUE TITLE
error LNK2019 unresolved external symbol when mex parts of opencv_contrib

### ISSUE THREAD

**Issue by Cyanyanyan** [kyamagu/mexopencv#220]
I just follow the mexopencv wiki instructions step to step to complete the configuration, everything goes well at the start, but there seems to be something wrong when i do "mexopencv.make('opencv_path','C:\OpenCV300\build\install', 'opencv_contrib',true)". I have tried many times but keep getting the following errors(just an example):

mex -O -largeArrayDims   -I'D:\Program Files\opencv300\mexopencv\include' -I'D:\Program Files\opencv300\mybuild64\install\include' -L'D:\Program Files\opencv300\mybuild64\install\x64\vc11\lib'  -lopencv_bgsegm300 -lopencv_calib3d300 -lopencv_core300 -lopencv_features2d300 -lopencv_flann300 -lopencv_hal300 -lopencv_highgui300 -lopencv_imgcodecs300 -lopencv_imgproc300 -lopencv_latentsvm300 -lopencv_ml300 -lopencv_objdetect300 -lopencv_optflow300 -lopencv_photo300 -lopencv_shape300 -lopencv_stitching300 -lopencv_superres300 -lopencv_video300 -lopencv_videoio300 -lopencv_videostab300 -lopencv_xfeatures2d300 -lopencv_xphoto300 'D:\Program Files\opencv300\mexopencv\opencv_contrib\src\+cv\private\LATCH_.cpp' 'D:\Program Files\opencv300\mexopencv\lib\MxArray.obj' 'D:\Program Files\opencv300\mexopencv\lib\mexopencv_features2d.obj' 'D:\Program Files\opencv300\mexopencv\lib\mexopencv_ml.obj' -output 'D:\Program Files\opencv300\mexopencv\opencv_contrib\+cv\private\LATCH_'
使用 'Microsoft Visual C++ 2012' 编译。
错误使用 mex
   正在创建库 D:\Program Files\opencv300\mexopencv\opencv_contrib\+cv\private\LATCH_.lib 和对象 D:\Program
   Files\opencv300\mexopencv\opencv_contrib\+cv\private\LATCH_.exp
LATCH_.obj : error LNK2019: 无法解析的外部符号 "struct cv::Ptr<class cv::xfeatures2d::LATCH> __cdecl createLATCH(class std::_Vector_const_iterator<class
std::_Vector_val<struct std::_Simple_types<class MxArray> > >,class std::_Vector_const_iterator<class std::_Vector_val<struct
std::_Simple_types<class MxArray> > >)"
(?createLATCH@@YA?AU?$Ptr@VLATCH@xfeatures2d@cv@@@cv@@V?$_Vector_const_iterator@V?$_Vector_val@U?$_Simple_types@VMxArray@@@std@@@std@@@std@@0@Z)，该符号在函数
mexFunction 中被引用
D:\Program Files\opencv300\mexopencv\opencv_contrib\+cv\private\LATCH_.mexw64 : fatal error LNK1120: 1 个无法解析的外部命令

I am using MatlabR2014a(x64)+VS2012+OX Win7. so can anybody help me?

**Comment by amroamroamro** [comment]
Two things I noticed:
- the path in the make call `'C:\OpenCV300\build\install'` doesn't match the path in the output you've shown `'D:\Program Files\opencv300\mybuild64\install'`
- it is preferred to build OpenCV and mexopencv somewhere where you have user permissions, i.e avoid using system protected folders like "Program Files" otherwise you'll have to run MATLAB "as administrator".

As for the error, it is a linking error complaining that `createLATCH` function was not found (this is conditionally defined in `include/mexopencv_features2d.hpp` if `xfeatures2d` module was available).

If I had to guess, you previously started a build of mexopencv without `opencv_contrib`.. If that's the case, the solution is to run `mexopencv.make('clean',true)` before you run `mexopencv.make` again (or use the 'force' option).

**Comment by Cyanyanyan** [comment]
Ohhhh thx very much for you nice guy~ just as you guess I first run mexopencv.make('opencv_path', 'D:\Program Files\opencv300\mybuild64\install') and then run mexopencv.make('opencv_path','D:\Program Files\opencv300\mybuild64\install', 'opencv_contrib',true). I have thought the two parts are seperate...Oh I'm so silly= =||

Thx for your solution, it's very helpful. Now everything is OK :)
