### ISSUE TITLE
Cannot use SIFT or SURF, but ORB is fine in the example "feature_homography_demo.m"

### ISSUE THREAD

**Issue by realhire** [kyamagu/mexopencv#234]
I got a error:
Undefined function or variable 'SURF_'

I used Matlab 2015b which has the toobox "computer vision system toolbox" and opencv 3.1.0 in windows 10 and vs2013 (which is not the default vs in the opencv/build/. I am too lazy to recompile. I will try to install vs2012 later.)

You told me to try opencv contri, so I can use nonfree module. I will try it later, but could you tell me the reason to do that? What does the "nonfree" mean? It means that I need to do the extra work to use it?

I know this question is stupid, and just want to know it. 

Thanks!

**Comment by kyamagu** [comment]
@realhire 

_Short answer_: OpenCV removed `SIFT` and `SURF` API and you cannot use them without extra work.

_Longer answer_: The OpenCV library made a significant change in version 3.0, and a lot of low-quality or experimental functions have been moved to [OpenCV contrib](https://github.com/Itseez/opencv_contrib). `SIFT` and `SURF` are among them, perhaps due to the potential licensing issue. `mexopencv` has support for them, but you will need to first [compile OpenCV with the extra modules](https://github.com/Itseez/opencv_contrib). Once compiled the extra modules, in `mexopencv`, you can follow the instruction in [Wiki](/kyamagu/mexopencv/wiki).

**Comment by realhire** [comment]
Great! I can use SIFT and SURF now!
