### ISSUE TITLE
Octave warnings related to mexopencv

### ISSUE THREAD

**Issue by AvinoamK** [kyamagu/mexopencv#239]
Hi,

after addpath ('C:\mexopencv') I get in Octave 4.0.1+ (development branch) the
following warnings

warning: function .\+cv\glob.m shadows a built-in function
warning: function .\+cv\norm.m shadows a built-in function
warning: function .\+cv\resize.m shadows a built-in function
 
Maybe these names should be changed to avoid this overlapping.

Thanks,

Avinoam

**Comment by kyamagu** [comment]
@AvinoamK Thanks for reporting this. I'm not familiar with the current status of Octave implementation of namespace functions and `import`, but this looks like rather a bug in Octave. Check whether if `resize` is calling the built-in function or `cv.resize`.

**Comment by amroamroamro** [comment]
@AvinoamK 
Just to clear this up, in MATLAB and Octave we only add the root folder to the `path` (you do not add the +folder itself, only its parent folder). So in this case you should be doing:

```matlab
>> addpath('C:\mexopencv')
>> which cv.norm  % C:\mexopencv\+cv\norm.(mex|m)
>> which norm     % builtin function
```

The mexopencv functions/classes will be called using the `cv` prefix (e.g `cv.norm`), so there is no conflict with built-in functions of the same name (unless of course you do `import cv` which I advice against).

---

One minor detail: due to an [open bug][1] in Octave (I last checked version 4.0.0), we are forced to also add the private directory located inside +cv package folders. So in Octave, for now you have to do:

```matlab
% only for Octave
>> addpath('C:\mexopencv')
>> addpath('C:\mexopencv\+cv\private')
```

This doesn't affect functions like `cv.norm`, only classes (like `cv.ORB`) and their associated MEX-files under the "private" directory. This has the potential to shadow builtins, but we are using names ending with underscore for the MEX-files (like `ORB_.mex`) to minimize the potential of name clashing. As a result, we are still safe with no conflicts...

So either way, the warnings you see are harmless, and in fact no builtin functions are being shadowed. I would say this a false-positive/bug in `addpath` of Octave!

[1]: http://savannah.gnu.org/bugs/?45444

**Comment by AvinoamK** [comment]
Thanks for the very detailed explanation. 
Indeed norm is Octave's norm and cv.norm is mexopencv norm, and there is no shadowing.
Meanwhile, I used 
warning ('off', 'Octave:shadowed-function')
to stop these warnings.
I have opened a bug on this (https://savannah.gnu.org/bugs/index.php?47622)

BTW, in the documentation there should be a note  that for Octave under Windows, 
OpenCV should be compiled with mingw compiler like Code::Blocks  and not with Visual Studio 
((outdated) explanation how to do it in
http://jatb181.blogspot.co.il/2014/06/install-opencv-248-with-codeblocks.html) 

Thanks again.

**Comment by amroamroamro** [comment]
There appears to be a existing bug report regarding the `addpath` warnings: https://savannah.gnu.org/bugs/?46849

---

Now to compile OpenCV and mexopencv for Octave under Windows, you should use the MinGW GCC compiler included with Octave, not some other distribution of MinGW. This is important because there are several exception models (DWARF vs. SJLJ) and threading models (pthreads vs. native win32 threads). Mixing these things can result in compilation/linking errors...

So if Octave/Windows was downloaded under `c:\octave`, you'll find the compilers in `c:\octave\bin\g++.exe`. Octave 4.0.0 comes with gcc 4.9.2, while Octave 4.0.1 comes with gcc 4.9.3.

For what it's worth, I provide a precompiled version of opencv + opencv_contrib 3.1.0 in my opencv fork. This is used by the CI tests (see `appveyor.yml`). You can download those in addition to the mexopencv build artifacts from:

- https://github.com/amroamroamro/opencv/releases/tag/3.1.0
- https://ci.appveyor.com/project/kyamagu/mexopencv/build/artifacts

So grab `mexopencv.7z` as well as `build_mingw_x86.7z`. These can be used directly with Octave 4.0.0 on Windows.

**Comment by AvinoamK** [comment]
@amroamroamro 

Thanks you very much. I will download these files.
