### ISSUE TITLE
Aruco from opencv_contrib

### ISSUE THREAD

**Issue by RGring** [kyamagu/mexopencv#254]
Hello,
Does mexopencv-mex-file-generation support the aruco-module?
When I create the mex-files the aruco.lib is found. But I can't find any functions.

mex -O -largeArrayDims   -I'C:\OpenCV\mexopencv\include' -I'C:\OpenCV\build\install\include' -L'C:\OpenCV\build\install\x64\vc10\lib'  -lopencv_aruco310 ...

Thanks already!
RGring

**Comment by amroamroamro** [comment]
Unfortunately no. We're gradually adding more opencv-contrib modules, but we haven't gotten to the aruco module yet.

Also this module is trickier to wrap in a general way than other modules, because the [API exposed] is very C++ oriented, with C++ objects (non-POD types) passed around across function boundaries... 

[1]: http://docs.opencv.org/3.1.0/d9/d6a/group__aruco.html

**Comment by RGring** [comment]
I see. That's a pitty. So I'll have to go with python.

**Comment by amroamroamro** [comment]
@RGring we've recently added aruco to mexopencv in #276, see https://github.com/kyamagu/mexopencv/issues/270#issuecomment-254163106.

**Comment by RoyiAvital** [comment]
The problem is still there with OpenCV 3.4 + OpenCV Contrib 3.4 and the latest MexOpenCV.

It seems the Make process in MATLAB assumes the `opencv2/aruco.hpp` file will be available in the `<OpenCVFolder>build\include\opencv2` folder.
Yet it only exists in the `<OpenCVFolder>build\install\include\opencv2`.
