### ISSUE TITLE
undefined reference to `cv::Moments::Moments'

### ISSUE THREAD

**Issue by superhans** [kyamagu/mexopencv#258]
When I run your demo code : 

```
#include "mexopencv.hpp"
void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    // Check arguments
    nargchk (nlhs<=1 && nrhs==1);

    // Convert MxArray to cv::Mat
    cv::Mat mat = MxArray(prhs[0]).toMat();

    // Do whatever you want

    // Convert cv::Mat back to mxArray*
    plhs[0] = MxArray(mat);
}
```

using the following command : 
`mex -L/usr/local/lib -L/homes/Softwares/mexopencv/lib -lopencv_core -lMxArray testMexOpencv.cpp`

I get the following error : 
```
Error using mex
/homes/manjunatha/UBUNTU_PANDORA/Softwares/mexopencv/lib/libMxArray.a(MxArray.o): In function `MxArray::toMoments(unsigned long) const':
MxArray.cpp:(.text+0x2c1a): undefined reference to `cv::Moments::Moments(double, double, double, double, double, double, double, double, double, double)'
collect2: error: ld returned 1 exit status
```

I'm running Ubuntu 14.04, Matlab 2016a, OpenCV 3.1
What do you think is the problem ?

**Comment by amroamroamro** [comment]
That's because `cv::Moments` class is only declared in [core][1] but the definition is actually in [imgproc][2] module. Therefore you'll have to link against both `-lopencv_core -lopencv_imgproc`.

Also your command is missing the include path to header files, i.e `-I/path/to/include` (for both OpenCV and mexopencv).

Note that you can simply place your file `testMexOpencv.cpp` next to the existing mexopencv source files and run the makefile, it will pick it up and issue the correct mex command.

[1]: https://github.com/Itseez/opencv/blob/3.1.0/modules/core/include/opencv2/core/types.hpp#L838
[2]: https://github.com/Itseez/opencv/blob/3.1.0/modules/imgproc/src/moments.cpp#L450

**Comment by superhans** [comment]
Hey, thanks for your response. I initially linked it with all the shared libraries (i.e., the entire output of `pkg-command --cflags --libs opencv`). I used the include path for both openCV and mexopenCV. 

But, it gave the same error. 

I solved it (temporarily) by commenting out the `toMoments` function in `MxArray.cpp`. I also removed `HuMoments.cpp` and `HuMoments.m` from` +cv `and `src/+cv` (because they were calling `toMoments`, and I don't think I need `HuMoments`). 

Then I ran `make` again.

**Comment by amroamroamro** [comment]
Perhaps you had a stale libMxArray, have you tried to clean and recompile (i.e `make clean && make`)?

Assuming you installed OpenCV correctly, the makefile should work straight away without having to modify any source files...

So the question is how did you obtain OpenCV? Are you using the correct version (both opencv and mexopencv)? What is the exact output of `pkg-config`?

**Comment by superhans** [comment]
Yes, I did clean and make. I believe I have installed OpenCV correctly (3.1). I am using the latest version of mexopencv, which I believe is compatible with OpenCV 3.1

The output of `pkg-config` is ```
-I/usr/local/include/opencv -I/usr/local/include  -L/usr/local/lib -lopencv_shape -lopencv_stitching -lopencv_objdetect -lopencv_superres -lo
pencv_videostab -lippicv -lopencv_calib3d -lopencv_features2d -lopencv_highgui -lopencv_videoio -lopencv_imgcodecs -lopencv_video -lopencv_ph
oto -lopencv_ml -lopencv_imgproc -lopencv_flann -lopencv_core  
```

One other interesting thing to note is that one of my lab-mates was also working on mexopencv last year with OpenCV 2.4.9. When I was going through his code, in `MxArray.cpp`, co-incidentally, he had commented out `toMoments()`. That led me to my temporary fix.

**Comment by amroamroamro** [comment]
The output of `pkg-config` looks correct to me... Just to confirm the right version, please also check:

``` sh
$ pkg-config --modversion opencv
```

Now let's try this one more time. Run the following in a shell terminal (all in one line):

``` sh
$ mex -largeArrayDims -cxx -I/path/to/mexopencv/include `pkg-config --cflags opencv`
   testMexOpencv.cpp -L/path/to/mexopencv/lib -lMxArray `pkg-config --libs opencv`
```

Note that the order of arguments is important, and the libraries must come after the source/object files. Also note that the linker works from left to right, so put your libraries first (MxArray), followed by their lib dependencies (opencv).

---

As I said before this is correctly done in the makefile, and it should be working as is (we do in fact run [continuous integration](https://travis-ci.org/kyamagu/mexopencv) tests to make sure everything compiles and runs just fine against the latest 3.1.0 version).

Otherwise I suspect something wrong in your setup, and perhaps you should start over (uninstall both opencv and mexopencv and start fresh).

**Comment by superhans** [comment]
Wow. It compiled successfully with I changed it to the order you prescribed !!
