### ISSUE TITLE
OpenCV with Matlab2015a and Visual C++ 2012 Mexing issue

### ISSUE THREAD

**Issue by nbibin001** [kyamagu/mexopencv#261]
Hi 
I was trying to get the OpenCV going with Matlab 2015a.
I have a 64 bit windows machine, 64 bit Matlab 2015a and Microsoft Visual C++ 2012 (C) coimpiler.
So as per the instructions I have extracted the opencv-3.1.0.exe to C:\opencv. And in the build folder
C:\opencv\build\x64 I could see vc12 and vc14 folders. 

Then downloaded the mexopencv-master folder and extracted under C:\Software\OpenCV\mexopencv-master.

Then opened Matlab 2015a and added the path to the folder C:\Software\OpenCV\mexopencv-master and tried to run the
make script mexopencv.make. It threw up an error saying that 

"Error using mexopencv.make>pkg_config (line 294)
OpenCV library path not found: C:\opencv\build\x64\vc11\lib"

Upon further analysis it looks like the command used in make.m 
cc = mex.getCompilerConfigurations('C++', 'Selected') 
returns the cc.Version as 11 but I dont have the vc11 folder under
C:\opencv\build\x64 when the  opencv-3.1.0.exe is extracted.

I am not sure if I use a different version of opencv exe it will show up the vc11 folder.

After this I have made some changes in the make.m file to select the vc12 folder for mexing.(Not sure if this is the 
right thing to do). Then it started mexing all the files and completed successfully. But after that when I tried to
run the facedetect.m it gave an error as below.

>>run('C:\Software\OpenCV\mexopencv-master\samples\facedetect.m')
Invalid MEX-file 'C:\Software\OpenCV\mexopencv-master\+cv\private\CascadeClassifier_.mexw64': The specified
module could not be found.

Error in cv.CascadeClassifier (line 113)
            this.id = CascadeClassifier_(0, 'new');

Error in facedetect (line 8)
classifier = cv.CascadeClassifier(xml_file);

Error in run (line 64)
evalin('caller', [script ';']);

Really appreciate any help/suggestions to resolve this.

**Comment by amroamroamro** [comment]
Here is a table of Visual Studio products and their corresponding version numbers:

| Product name       | Version number |
| ------------------ | -------------- |
| Visual Studio 2015 | vc14           |
| Visual Studio 2013 | vc12           |
| Visual Studio 2012 | vc11           |
| Visual Studio 2010 | vc10           |
| Visual Studio 2008 | vc9            |
| Visual Studio 2005 | vc8            |

*(version vc13 was skipped, bad luck superstitions!)*

---

You see in order to reduce the file size, `opencv-3.1.0.exe` contains binaries only for the last two releases (i.e. vc14 and vc12). Since you're using VS2012, the `mexopencv.make` fails to find the expected folder (vc11). You have two options:

- compile opencv 3.1.0 from source yourself using the compiler version you have (VS2012). See [here](https://github.com/kyamagu/mexopencv/wiki) for detailed instructions.
- upgrade VS to the newer version if you want to use the opencv installer. You can download the full VS2013/2015 community edition [for free](http://go.microsoft.com/fwlink/?LinkId=518338).

**Comment by nbibin001** [comment]
Hey this is great instructions, I decided to choose the first option to compile opencv 3.1.0 using Visual Studio version I have. I have got it compiled and am able to play with Open CV in Matlab 2015a now . Thank you so much for the quick help.
