### ISSUE TITLE
 make: *** [+cv/private/SuperResolution_.mexa64] error 255

### ISSUE THREAD

**Issue by yiran-THU** [kyamagu/mexopencv#269]
@kyamagu 
hello,when I make mexopencv in MATLAB,I come across following problem:

```
/home/yiran/download/mexopencv/src/+cv/private/SuperResolution_.cpp:76:25: error: template argument 1 is invalid
     Ptr<FarnebackOpticalFlow> createFarnebackOpticalFlow(
                   ^
/home/yiran/download/mexopencv/src/+cv/private/SuperResolution_.cpp: In function ‘int {anonymous}::createFarnebackOpticalFlow(bool, std::vector<MxArray>::const_iterator, std::vector<MxArray>::const_iterator)’:
/home/yiran/download/mexopencv/src/+cv/private/SuperResolution_.cpp:83:29: error: template argument 1 is invalid
     Ptr<FarnebackOpticalFlow> p = (use_gpu) ?
                  ^
/home/yiran/download/mexopencv/src/+cv/private/SuperResolution_.cpp:83:33: error: invalid type in declaration before ‘=’ token
     Ptr<FarnebackOpticalFlow> p = (use_gpu) ?
                   ^
/home/yiran/download/mexopencv/src/+cv/private/SuperResolution_.cpp:85:33: error: invalid user-defined conversion from ‘cv::Ptr<cv::superres::FarnebackOpticalFlow>’ to ‘int’ [-fpermissive]
           createOptFlow_Farneback();
                    ^
... ...
/home/yiran/download/mexopencv/src/+cv/private/SuperResolution_.cpp:309:45: error: base operand of ‘->’ is not a pointer
                   s.set("Flags",            pp->getFlags());
                                     ^

make: *** [+cv/private/SuperResolution_.mexa64] 错误 255
```

My OS is ubuntu 14.04.
My MATLAB version is R2016a.
My OPENCV version is 3.1.0

I hope I can get help here,
Thank you!

**Comment by yiran-THU** [comment]
when I use terminal ，it reports "ar -crs lib/libMxArray.a lib/mexopencv_features2d.o lib/mexopencv_ml.o lib/mexopencv_shape.o lib/mexopencv_stitching.o lib/mexopencv_videostab.o lib/MxArray.o
"

**Comment by yiran-THU** [comment]
@amroamroamro 
Thank you for your reply!
I have fixed the formatting of my bug report to make it clear and correct.
I have downloaded the opencv from [here](https://github.com/Itseez/opencv/archive/2.4.13.zip), then I unpacked it and made a "bulid" folder in the root directory of opencv.
After finish that,I type
```
mkdir release
cd release
cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local ..
make
sudo make install
```
in the terminal.
this is how I compiled/installed opencv

As for compile mexopencv, I type "mexopencv.make" in matlab command window, the bug report is shown above.
I also type `make MATLABDIR=/usr/local/MATLAB/R2016a`in terminal, but I still failed.The bug report in terminal is 
```
ar -crs lib/libMxArray.a lib/mexopencv_features2d.o lib/mexopencv_ml.o lib/mexopencv_shape.o lib/mexopencv_stitching.o lib/mexopencv_videostab.o lib/MxArray.o
```
.
Next time,I want to try
```
sudo apt-get install libopencv 
make MATLABDIR=/opt/local/MATLAB/R2016a
```
command in terminal,

Thanks again!

**Comment by amroamroamro** [comment]
As I suspected, you're not using the correct opencv version. The URL you mentioned is for version 2.4.13. You need to grab [3.1.0](https://github.com/Itseez/opencv/archive/3.1.0.zip) instead if you want to work with the latest mexopencv.

Also since you're on Ubuntu 14.04, trying to install opencv from the Ubuntu archive won't be of help either, seeing that it ships with the old [opencv 2.4.8](http://packages.ubuntu.com/trusty/libopencv-dev).

You want to compile opencv from source like you did, only you must use the version expected 3.1.0.

Once opencv is built and installed, check that `pkg-config --cflags --libs opencv` gives the correct output, which is how we locate opencv in the mexopencv makefile.

**Comment by amroamroamro** [comment]
@yiran-THU Was the problem solved? Did you try building against the correct 3.1.0 version?

**Comment by yiran-THU** [comment]
@amroamroamro 
NO! I have tried every version of OPENCV,none of them work.
I think it is not the version problem.

**Comment by amroamroamro** [comment]
@yiran-THU 
You don't want to try every version of OpenCV, you must use the exact 3.1.0 version to work with the latest mexopencv.

OpenCV is a very active project, with daily changes commited. Some of these changes break the public API interface (i.e its version bumped). We cannot keep up with the bleeding-edge dev-version, so we only target final stable release. Currently at this time, v3.1.0 is the latest stable version published, which we test against...

Note that opencv and opencv_contrib are released in sync, so the same goes for the contrib modules if you're using them.

---

So please double-check that you are indeed using OpenCV 3.1.0.
I'm pretty sure that mexopencv compiles fine against this version, because we continuously test it whenever new code is pushed (both Linux and Windows).

You can see our Travis [build script](https://github.com/kyamagu/mexopencv/blob/master/.travis.yml) and the build history [here](https://travis-ci.org/kyamagu/mexopencv): we build opencv+opencv_contrib 3.1.0 from source, compile mexopencv against it, then run the complete test suite (obviously we use Octave in the tests since MATLAB can't be freely installed on the cloud).
