### ISSUE TITLE
Compiling mexopencv with 64bit Octave

### ISSUE THREAD

**Issue by AvinoamK** [kyamagu/mexopencv#286]
I have checked mexopencv with octave-4.2.0-rc3 and it compiled and passed all the tests.

How do I build mexopencv with 64 bit Octave? Octave-4.2.0-rc3-w64 is now available in alpha.gnu.org

Thanks,

Avinoam

**Comment by amroamroamro** [comment]
The build process is really the same as with the 32-bit version of Octave...

First you build OpenCV from source using the GCC compilers included with Octave, then you build mexopencv against it with the usual `mexopencv.make` call.

**Comment by amroamroamro** [comment]
@AvinoamK 
I updated the wiki to include instructions for Octave/Windows.

**Comment by AvinoamK** [comment]
Thank you very much,

Avinoam

**Comment by AvinoamK** [comment]
Is it possible to upload the 64 bit opencv to
https://github.com/amroamroamro/opencv/releases/tag/3.1.0 ?

**Comment by amroamroamro** [comment]
Have you tried the [instructions](https://github.com/kyamagu/mexopencv/wiki/Installation-(Windows,-Octave,-OpenCV-3)) posted? You should be able to compile OpenCV yourself..

The binaries over there are not exactly official releases. These are meant to reduce time taken when running mexopencv CI tests and avoid the time limit in the free plan of AppVeyor (we don't have to compile the same OpenCV version each time a build is triggered).

Since we don't use the 64-bit beta of Octave in the CI tests, I don't plan on uploading x64/mingw opencv binaries. I don't actually compile it myself, I rely on AppVeyor in my fork to build it in the cloud and save those build artifacts (combination of batch/powershell scripts):

https://github.com/amroamroamro/opencv/blob/tag_3.1.0/appveyor.yml
https://ci.appveyor.com/project/amroamroamro/opencv/history

**Comment by AvinoamK** [comment]
Thanks, I will try to build 64-bit using the instruction in the wiki.

**Comment by amroamroamro** [comment]
@AvinoamK 
Were you successful in building against octave-4.2.0-w64 using the posted instructions?

**Comment by AvinoamK** [comment]
Unfortunately, I did not have time, yet.
Hope to do it next week
Thanks,

**Comment by AvinoamK** [comment]
Hi,
Using your instructions, building OpenvCV 64-bit and building mexopencv 
against the final octave-4.2.0-w64 was successful.

after test:

 Totals:
  1102 Passed, 0 Failed
  Elapsed time is 615.524411 seconds.

Thank you

**Comment by amroamroamro** [comment]
Excellent, thanks for testing it.
