### ISSUE TITLE
MEXOPENCV and Octave 4.2.0

### ISSUE THREAD

**Issue by AvinoamK** [kyamagu/mexopencv#296]
Octave 4.2.0 have been released. I have checked mexopencv with Octave 4.2.0 and it passed all the tests.

Question: There are some HACKs in the code to overcome some Octave bugs. Some of them
have been fixed now. Do you intend to delete these workarounds, or keep them to support previous versions of Octave?

**Comment by amroamroamro** [comment]
Nice, thanks for checking.

For now I would keep all existing [HACKs](https://github.com/kyamagu/mexopencv/search?q=HACK) to avoid breaking the CI tests; especially the Linux/Travis one since we use [`ppa:octave/stable`](https://launchpad.net/~octave/+archive/ubuntu/stable) to install Octave on Ubuntu. This PPA only offers the 4.0.2 version at the moment.

I could update the Appveyor tests to use the newest Octave 4.2.0 binaries instead of the current 4.0.3. I'll need a couple of days to look into it.
