### ISSUE TITLE
create custom aruco board

### ISSUE THREAD

**Issue by RGring** [kyamagu/mexopencv#335]
I would like to create a custom aruco board, because I already have an installed grid at a wall that I would like tu use for calibration.
Is there a way to create a custom aruco board like here: http://docs.opencv.org/trunk/d4/db2/classcv_1_1aruco_1_1Board.html ? I didn't find anything...

Thanks already!

**Comment by RGring** [comment]
Okay, I already found the solution. A custom board can be created through the option 'Board'.

Comment for that: 
% * __board__ layout of markers in the board. The layout is composed by the
%       marker identifiers and the positions of each marker corner in the
%       board reference system.
%       You can specify the board as a cell-array that starts with the
%       type name followed by option arguments `{Type, ...}`.
%       There are three types of boards available:
%       * __Board__ `{'Board', objPoints, dictionary, ids}`.
%             Creates a board of markers.
%       * __GridBoard__ `{'GridBoard', markersX, markersY, markerLength, markerSeparation, dictionary}`.
%             Creates a a GridBoard object given the number of markers in each
%             direction and the marker size and marker separation.
%       * __CharucoBoard__ `{'GridBoard', squaresX, squaresY, squareLength, markerLength, dictionary}`.
%             Creates a CharucoBoard object given the number of squares in
%             each direction and the size of the markers and chessboard
%             squares.

% ## Options for Board
% * __objPoints__ array of object points of all the marker corners in the
%       board, i.e. their coordinates with respect to the board system. Each
%       marker include its 4 corners in CCW order
%       `{{[x1,y1],[x2,y2],[x3,y3],[x4,y4]}, ..}`.
% * __dictionary__ the dictionary of markers employed for this board. This is
%       specified in the same format described in cv.detectMarkers.
% * __ids__ vector of the identifiers of the markers in the board (same size
%       as `objPoints`). The identifiers refers to the board dictionary

**Comment by amroamroamro** [comment]
Right.

[cv.estimatePoseBoard][1] explains how to specify a `Board`, [cv.detectMarkers][2] explains how to specify a `Dictionary`.

In addition you can pass a struct with fields instead of a cell-array of key/values. This is to accomodate [cv.boardDump][3] and [cv.dictionaryDump][4] functions, that way you can give their output (struct) as input to other functions.

[1]: https://github.com/kyamagu/mexopencv/blob/master/opencv_contrib/%2Bcv/estimatePoseBoard.m
[2]: https://github.com/kyamagu/mexopencv/blob/master/opencv_contrib/%2Bcv/detectMarkers.m
[3]: https://github.com/kyamagu/mexopencv/blob/master/opencv_contrib/%2Bcv/boardDump.m
[4]: https://github.com/kyamagu/mexopencv/blob/master/opencv_contrib/%2Bcv/dictionaryDump.m
