### ISSUE TITLE
Unable to build mexopencv

### ISSUE THREAD

**Issue by Ghada26** [kyamagu/mexopencv#346]
I'm trying to use mexopencv 3.2.0. To do so, I successfully built opencv3.2.0 and opencv_contrib 3.2.0 using visual studio community 2015 as recommended in the wiki page. My system is  windows 7.
However, when I try to build mexopencv within Matlab R2012b, I get the following error:
```
Error using mexopencv.make>pkg_config (line 316)
OpenCV library path not found: C:\dev2\build\install\x64\vc11\lib

Error in mexopencv.make>mex_options (line 256)
    [cv_cflags, cv_libs] = pkg_config(opts);

Error in mexopencv.make (line 81)
    mex_flags = mex_options(opts);
```
I don't understand why the path is `C:\dev2\build\install\x64\vc11\lib` instead of `C:\dev2\build\install\x64\vc14\lib`
How should I correct this issue?

Thank you

**Comment by amroamroamro** [comment]
If you run `mex -setup`, you will see the problem..
MATLAB R2012b doesn't detect VS2015 compilers. That's because it came out in 2012 three years before VS2015 was released.

- You're gonna have to manually edit mexopts *.bat config files to work with your VS version (you might find patches online like [this one][2] for VS2012).
As far as I know, MATLAB doesn't officially support the "community editions" of Visual Studio, so you're gonna have to account for that when you edit the config files.

- Otherwise you could switch to a compiler that your MATLAB version recognizes.
According to the [list of supported compilers][1], R2012b works with either VS2010 or WinSDK 7.1 ([the latter][4] can be downloaded for free)

Note: the MEX infrastructure changed in MATLAB R2014a, and is now using XML config files instead of BAT/STP files. I've [posted][3] modified config files to enable VS2017 support in R2016b, but that is in XML format, not sure if it helps in your case...

[1]: https://www.mathworks.com/support/sysreq/previous_releases.html
[2]: http://jimdavid.blogspot.com/2012/12/matlab-2012b-mex-setup-with-vs2012.html
[3]: https://gist.github.com/amroamroamro/ea4541d5621f3d62e67029e393e523a0
[4]: https://www.mathworks.com/matlabcentral/answers/101105-how-do-i-install-microsoft-windows-sdk-7-1

**Comment by Daphnee** [comment]
Thank you for your detailed answer. The simplest way was to use a more recent version of matlab and the problem has been solved after I installed Matlab R2017a.

**Comment by Ghada26** [comment]
Thank you for your detailed answer. The simplest way was to use a more recent version of matlab and the problem has been solved after I installed Matlab R2017a.

**Comment by amroamroamro** [comment]
yep, that works too :)
