### ISSUE TITLE
Checkerboard corners are not offset to be in accord with matlab first element (1 and not 0)

### ISSUE THREAD

**Issue by HagegeR** [kyamagu/mexopencv#348]
I just made a quick verification of the differences between matlab and mexopencv results on _findChessboardCorners_ and _find4QuadCornerSubpix_.
The code has no part where it offsets the corners result to compensate the difference between matlab and C++ in the first element of a matrix (0 in C++ and 1 in matlab).
The results I see myself seems all to be offset by a pixel in each directions, thus I wanted to know if it could be rectified, maybe other functions suffer from similar problems (if I'm right)...

**Comment by amroamroamro** [comment]
This is by design: https://github.com/kyamagu/mexopencv/wiki/Gotchas

The issue of 0-based vs. 1-based indexing was raised a while back: https://github.com/kyamagu/mexopencv/issues/23. I agree with Kota's response in that it is best to leave the raw inputs/output of OpenCV as-is, and not attempt to "fix" them.

In your case, if you were to plot the corners using OpenCV's functions like `cv.drawChessboardCorners` or `cv.circle` the results would be correct (because these functions assume (0,0) as origin as well), only if you plot them using MATLAB's drawing functions (`plot`, `line`, `scatter`, etc.) then you would have to *offset by one*.

As was said, the difference in indexing affects most the API not just the two functions you mentioned, and it's just something you have to keep in mind when working with mexopencv. As long as the arguments are passed around between opencv functions it's all good. When you pass them to MATLAB drawing functions and the like, you must account for the difference in convention.

**Comment by HagegeR** [comment]
thank you for the quick reply!
Yes my intention was to pass them to matlab and rely less on openCV where possible...
Ok, I'll keep that in mind
