### ISSUE TITLE
Aruco Does not Contain any Functions

### ISSUE THREAD

**Issue by arb93** [kyamagu/mexopencv#350]
Hi, 

I successfully installed opencv 3.0 with python 3.5 and have the aruco module within the contrib folder.

However, upon typing help(cv2.aruco), I see that there are no available functions. Only dictionaries.

Any help would be appreciated.

Thanks,

Alex

**Comment by kyamagu** [comment]
@arb93 Are you talking about Python API? mexopencv is a Matlab wrapper. Inappropriate to post your question here.

**Comment by amroamroamro** [comment]
@arb93 
As explained, mexopencv is a MATLAB library.
We do expose the aruco module in mexopencv. You can find several samples `aruco_*.m` here:
https://github.com/kyamagu/mexopencv/tree/master/opencv_contrib/samples

As for Python, you must use opencv/opencv_contrib version 3.2.0 and up (the python wrappers were fixed in that version). You need to compile both from source.

Please direct any further question about the Python lib to the right place: http://answers.opencv.org/
