### ISSUE TITLE
Aruco and Ximgproc errors

### ISSUE THREAD

**Issue by wajahat57** [kyamagu/mexopencv#359]
Hi
It appears that aruco is not in OpenCV 3.3.0 world version. Therefore, I encountered an error: `aruco.hpp no such file or directoy`. To resolve this, I had to delete aruco from include and src folders in opencv_contrib.3.3.0.

Once again at: `FastHoughTransform.cpp`
```
path_to_root_folder\mexopencv-master\opencv_contrib\src\+cv\FastHoughTransform.cpp(9): fatal error C1083:
Cannot open include file: 'opencv2/ximgproc.hpp': No such file or directory
```

Don't know how to solve this. Perhaps some path issue somewhere

**Comment by amroamroamro** [comment]
The [official installers](http://opencv.org/releases.html) do not include "opencv_contrib" modules, only the main "opencv" modules.

So if you want to enable the contrib modules you must build opencv + opencv_contrib from source yourself, as explained in the [installation guide](https://github.com/kyamagu/mexopencv/wiki/Installation-%28Windows%2C-MATLAB%2C-OpenCV-3%29).

Otherwise you should be doing:

```matlab
addpath('C:\dev\mexopencv')
%rmpath('C:\dev\mexopencv\opencv_contrib')
mexopencv.make('opencv_path','C:\path\to\opencv-3.3.0\build', 'opencv_contrib',false)
```

**Comment by wajahat57** [comment]
ok. thanks. that explains it.
