### ISSUE TITLE
EM throws error on predict2

### ISSUE THREAD

**Issue by Tarcisiofl** [kyamagu/mexopencv#360]
I'm getting the error message below, when I'm trying to run my code to predict if the pixel is part of a leaf or background:

`CvException [org.opencv.core.CvException: cv::Exception: /build/master_pack-android/opencv/modules/ml/src/em.cpp:569: error: (-215) sample.size() == Size(means.cols, 1) in function cv::Vec2d cv::ml::EMImpl::computeProbabilities(const cv::Mat&, cv::Mat*, int) const]`

The code, is here:

```
EM em = EM.create();
 em.setClustersNumber(2);
 em.setCovarianceMatrixType(EM.COV_MAT_DIAGONAL);
 em.trainEM(stackedPixels);

Mat mPredict = new Mat(1, 2, CvType.CV_64FC1);
mPredict.put(0,0,imgHSV.get(i,j)[1]);
mPredict.put(0,1,imgHSV.get(i,j)[2]);

double[] probabilities = em.predict2(mPredict, probs); // ERROR 
```

Anyone can help me?

**Comment by amroamroamro** [comment]
Is that the Java binding? Clearly not related to mexopencv...

You should ask help on [OpenCV Answers](http://answers.opencv.org/questions/).

---

FYI, this works fine in MATLAB:

```matlab
em = cv.EM();
em.ClustersNumber = 2;
em.CovarianceMatrixType = 'Diagonal';

X = [randn(50,2)+1; randn(50,2)-1];
em.trainEM(X);

[loglik, labels, probs] = em.predict2(X);
gscatter(X(:,1), X(:,2), labels)
```

Under the hood, we perform a loop over rows of `X` and call `predict2`, because the method only supports predicting one sample at a time:

> https://github.com/kyamagu/mexopencv/blob/master/src/%2Bcv/private/EM_.cpp#L273-L289
