### ISSUE TITLE
Bug in function MxArrayToVectorVec, cv::Vec "< _Tp, cn>" has no member "depth"

### ISSUE THREAD

**Issue by Tariq-Abuhashim** [kyamagu/mexopencv#368]
When compiling against OpenCV 3.3, arrowedLine.cpp returned an error:
In mexopencv.hpp line 342, cv::Vec has no member 'depth'.

Looking at OpenCV documentation and MxArray.hpp, cv::Vec<T,cn>::depth should be replaced by cv::DataDepth<T>::value.

In mexopencv.hpp :
line 342  -  arr.toMat(cv::Vec<T,cn>::depth).reshape(cn, 0).copyTo(vv);
line 342 +  arr.toMat(cv::DataDepth< T>::value).reshape(cn, 0).copyTo(vv);

All compiled successfully, then.

**Comment by amroamroamro** [comment]
As explicitly mentioned in the readme file, you **MUST** use OpenCV 3.3.0:

> https://github.com/kyamagu/mexopencv#opencv

I suspect you're using 3.3.1 or newer (master)... They've since deprecated `cv::DataDepth` and similar definitions in favor of `cv::traits::Depth` and `cv::traits::Type`.

Version 3.3.1 was [released](https://github.com/opencv/opencv/releases) a few days ago, a mexopencv update should be coming soon. In the mean time, use the correct [supported](https://github.com/kyamagu/mexopencv/releases) version.

**Comment by cornicione** [comment]
I meet the same problem.
Looking forward to the new version.

**Comment by amroamroamro** [comment]
fixed in latest version which targets OpenCV 3.3.1
