### ISSUE TITLE
Fisheye calibration?

### ISSUE THREAD

**Issue by vinodkhare** [kyamagu/mexopencv#378]
I want to contribute bindings for the fisheye module. I have a good idea about how to write the mex functions. But I would like to match the OpenCV C++ namespaces and add these to a `cv.fisheye` namespace in MATLAB. 

1. Is there interest in accepting pull request for the fisheye module?
2. If yes, does it make sense to add these to `cv.fisheye` namespace in MATLAB? How can I do so?

Thank you!

**Comment by amroamroamro** [comment]
Yes, contributions are welcome. Good news is that I already have the fisheye functions implemented, I just haven't gotten around to committing them.

I have the .cpp and .m files, but I'm missing unit-tests. You could help writing some tests if you're interested..

I'll clean the code a bit, and open a PR with what I have done so far.

**Comment by amroamroamro** [comment]
Regarding naming, I'm simply using a prefix (as in: `cv.fisheyeProjectPoints` and `cv.fisheyeUndistortPoints`, etc.).

Though it's possible to organize the functions under a nested namespace like you said (i.e `cv.fisheye.projectPoints`), it complicates things for the build scripts (`make.m`, `Makefile`, `UnitTest.m`, `MDoc.m`, ...), as they mostly assume a flat namespace with no duplicate names.

For instance, the way the makefile is currently implemented has a limitation: we can't have two C++ source files with the same name under different directories (e.g `src/+cv/projectPoints.cpp` and `src/+cv/+fisheye/projectPoints.cpp`).
It breaks because we use `vpath` to find rule prerequisites, which ends up picking the wrong cpp file...

https://github.com/kyamagu/mexopencv/blob/6f48774301bebf66c7efb66501b771aae3019a81/Makefile#L124-L135

https://github.com/kyamagu/mexopencv/blob/6f48774301bebf66c7efb66501b771aae3019a81/Makefile#L159-L165

**Comment by vinodkhare** [comment]
Thank you for clarifying that. 

I'd be happy to contribute (some, maybe not all) unit tests if you can point me to relevant dev branch.

**Comment by amroamroamro** [comment]
@vinodkhare 
Committed 3466923 in [cv331](https://github.com/kyamagu/mexopencv/tree/cv331) dev branch.

The unit tests are in `test/unit_tests/TestFisheye*.m` (see the TODO comments).

**Comment by amroamroamro** [comment]
merged in #390, we still need some unit-tests though..

**Comment by amroamroamro** [comment]
@sakts I don't know, but whether or not it does is really an opencv issue...

mexopencv is an OpenCV wrapper in MATLAB, we don't implement the algorithm ourselves, we just expose the existing C++ functions in an appropriate matlab interface.

PS: there's a module called [`ccalib`](https://docs.opencv.org/trunk/d3/ddc/group__ccalib.html) in opencv_contrib which covers additional cases like omnidirectional cameras. But we don't expose that module in mexopencv at the moment.
