### ISSUE TITLE
Color to depth mapping in Matlab

### ISSUE THREAD

**Issue by andriskuciks** [kyamagu/mexopencv#397]
This isn't an issue, its a question because I couldn't find any link to a Q&A forum. 
 I have a hybrid stereo system which consists of RGB camera and ToF camera. Both of the camera resolutions are set to 320x240. Right now I have one variable which consists of 76800 points with [x,y,z] information and an image of the same scene. I have done stereo calibration and have extrinsic and intrinsic parameters. How can I map a point to its corresponding color from the RGB image so I could get in the end a 3D colored point cloud of the scene? Is there an easy to use function or something else or i have to write a script to do this?

**Comment by amroamroamro** [comment]
[OpenCV Q&A](http://answers.opencv.org/questions/) and [Stack Overflow](https://stackoverflow.com/questions/tagged/opencv) are good places to ask questions.

---

Now if I understood correctly, you have 3D points coordinates and the corresponding colors from the image, so you could just use [`scatter3`](https://www.mathworks.com/help/matlab/ref/scatter3.html) to visualize the point cloud:

```matlab
% 3D coordinates
xyz = [..];  % 76800x3 matrix

% color image of the scene
img = [..];  % 240x320x3 uint8 array

% flatten image into 3 color columns (RGB triplets)
clr = reshape(double(img)/255, [], 3);

scatter3(xyz(:,1), xyz(:,2), xyz(:,3), 6, clr, '.')
axis tight vis3d
title('Point Cloud'); xlabel('X'); ylabel('Y'); zlabel('Z');
```

That's how we do it the mexopencv example: [`stereo_calibration_demo.m`](https://github.com/kyamagu/mexopencv/blob/master/samples/stereo_calibration_demo.m) ([published](http://amroamroamro.github.io/mexopencv/opencv/stereo_calibration_demo.html))

*PS: I'm assuming `xyz` points are stored in column-major order, if not you'll have to transpose the image before flattening it.*

**Comment by andriskuciks** [comment]
Not really corresponding colors for 3D points. Its a stereo system of ToF camera and RGB camera so there is a rotation and translation between the scenes of both cameras. The code provided dosen't take the translation and rotation in matter so the output of of scatter3 is pretty bad. How can I make it so that it takes rotation and translation in consideration as well?

**Comment by amroamroamro** [comment]
I'm not familiar with ToF cameras, but for a regular stereo pair you'd have two images of the same scene from each camera, one of the cameras being the origin of world coordinates. Use the image from that camera head for the colors, that should work right?

I guess you could also use the image from the 2nd camera, it's a matter of transforming XYZ points from coordinates of the 1st camera to the coordinates of the 2nd camera. You got that information in `R,T` as the output of `cv.stereoCalibrate`:

> http://amroamroamro.github.io/mexopencv/matlab/cv.stereoCalibrate.html

Then again I could be wrong, I'm no expert in calib3d..
Try asking on OpenCV Q&A or StackOverflow, those sites have a large audience of CV users.

**Comment by andriskuciks** [comment]
Okay. thanks anyways!

**Comment by amroamroamro** [comment]
Can you share sample data (xyz points, color images, and the stereo calibration output)?

**Comment by andriskuciks** [comment]
I can send you Matlab workspace where all the data you want is saved. Will that work for you?

**Comment by amroamroamro** [comment]
ok

**Comment by andriskuciks** [comment]
Its a close range application so the scene in the point clouds and RGB image  was approx 20cm away. The cl1 and cl2 are the calibrated point clouds, which have a correct Z value and compensated lens distortion. cl3 is the uncalibrated point cloud and the *_den are pointclouds after doing pcdenoise in Matlab. In stereo parameters the camera1 is RGB cam and camera2 is the ToF. If you need anything else please let me know. I'll be able to provide you with anything for the next hour. Afterwards I'll be able to help you only on Monday.
Regards, Andris
[rgb_points.zip](https://github.com/kyamagu/mexopencv/files/1884148/rgb_points.zip)

**Comment by amroamroamro** [comment]
I'm confused by the variables you have:

- What was exactly the output from the cameras?
- In `depth`, it looks like `depth(:,:,2)` is the depth map? what are the other channels?
- How did you build `cl*` point clouds?
- It seems you've used CVST functions, not mexopencv for the stereo calibration...

I tried plotting this, not sure if it's correct:

```matlab
z = double(depth(:,:,2))/255;
[x,y] = ndgrid(1:size(depth,1), 1:size(depth,2));
c = double(scene)/255;
%c = flip(c,1);
%c = flip(c,2);
scatter3(x(:), y(:), z(:), 6, reshape(c,[],3), '.')
axis vis3d
cameratoolbar('Show')
cameratoolbar('SetMode','orbit')
```

Move the camera around to get a better view and see for yourself...
Also I tried to flip the image along first/second/both dimensions, that's the commented lines.

Like I said, no guarantees if this is of any help :)

**Comment by andriskuciks** [comment]
Hi Amro! 
The outputs of the camera are multiple, it depends what kind of iformation you need. I'm using TI's supported Voxel Viewer to get the point clouds. All of the possible outputs are: 
- Ambient
- Amplitude
- Amplitude Average
- Amplitude Standard Deviation
- Depth (Z)
- Depth Average 
- Depth Standard Deviation
- Distance
- Flags
- Phase
- Phase Average
- Phase Standard Deviation
- Point cloud

I just select what type of output I want to see and just export it to Matlab. 
Yes the variable `depth` is a depth map. 

I just exported the point cloud as .pcd file from the Voxel Viewer.

I used Matlab stereo calibration tool, because I saw a lot of references where this app was used and the results where fine. Should I do the calibration using mexopencv? 

And thanks for your help. If you have any other suggestions or ideas, please share them :) Gonna try your code right away!

Regards, Andris

**Comment by andriskuciks** [comment]
Your supported code is actually really good. Now just have to figure out how to take into account the translation between the two cameras. Thank you vary much Amro. If you have any kind of ideas how to do it, please let me know! I appreciate your help!

**Comment by amroamroamro** [comment]
You keep mentioning the translation/rotation between the camera heads. I don't think it matters here because transforming the XYZ points will simply change the points from one coordinates system to another, the 3d points will still have the same shape (`[R t]` a rigid transformation).

Next let me get this right; the point cloud is generated directly by the camera, which you then export as .pcd file, and load into MATLAB I'm assuming using `pcread` function ?

Perhaps the color information is lost in the process of exporting/importing? Do you see the colors when you view the point cloud directly in the VoxelViewer tool?

Other than that, I'm afraid I'm out of ideas... You say you have a TI camera, perhaps you can try asking on their support forums: https://e2e.ti.com/support/sensor/optical_sensors/

Good luck.

**Comment by andriskuciks** [comment]
If I do the transformation, in the result it would give the XYZ points their corresponding color of the scene, wouldn't it? Right now I'm trying to align the scenes by just translating the RGB image using `imtranslate` so it fits the XYZ points but I believe it's not the correct way of doing it. 

Yes, I'm exporting point cloud as .pcd from the Voxel Viewer and then load it to a Matlab variable using `pcread`.

Unfortunately the point cloud in Voxel Viewer is only a greyscale information, because ToF  doesn't have a RGB sensor, thats why I have a RGB camera attached to the sensor.

**Comment by andriskuciks** [comment]
I managed to do the transformation and got the corresponding colors. The only thing is, that Y axis in the point cloud is about 60 pixels off,  and I do not know why. If you are interested I can share the code.
Regards Andris

**Comment by amroamroamro** [comment]
@andriskuciks sure

**Comment by andriskuciks** [comment]
Here you go 
[Color_cloud.zip](https://github.com/kyamagu/mexopencv/files/1915721/Color_cloud.zip)

**Comment by amroamroamro** [comment]
I need you to clarify something first, you have two cams (depth cam and RGB cam), which one is cam1 and which one is cam2?

I'm talking about when you did the stereo calibration with `estimateCameraParameters`, how did you assign the image points?

I'm asking because `stereoParams` returned will have the rotation/translation of cam2 relative to cam1, and this order matters..

When I load your MAT file and run `showExtrinsics(stereoParams_pi1)` I can see one camera on top of the other (2 on top of 1), but which one is which?

**Comment by andriskuciks** [comment]
Well when I used the Matlab stereo calibration app, I just uploaded the images from camera1 and images from camera2 seperately. Next the app detected the chessboard corners in both image pairs, then selected which and how many distortion coefficients I want to use and last just press calibrate. Last the app just generates a Matlab code from the calibration results. I hope I explained good enough. I believe that the app assigns the imagePoints variable automatically

**Comment by amroamroamro** [comment]
ok so you're using the "Stereo Camera Calibrator" app ([stereoCameraCalibrator](https://www.mathworks.com/help/vision/ref/stereocameracalibrator-app.html)), but this GUI still calls the same underlying function `estimateCameraParameters`.

When you start the app and click "Add Images" you get the dialog below, that's where you assign which one is camera 1 and camera 2:

![stereoCameraCalibrator](https://user-images.githubusercontent.com/83908/38892596-5ba1655e-4290-11e8-8167-9859bf25dc4e.PNG)

This is important because stereo calibration returns transformation of cam2 relative to cam1, i.e:

    x1 = R*x2 + t

where `x2` is 3D coordinates in camera2 frame and `x1` is in camera1 frame.

The problem is that you're using `[R t]` to transform the other way around. Do you see the problem now?

---

Here's your code simplified and fixed:

```matlab
load('color_cloud.mat')
clearvars -except stereoParams_pi1 cl1 scene2

% intrinsic params
A = stereoParams_pi1.CameraParameters1.IntrinsicMatrix';

% transformation matrix [R,t] (cam2-to-cam1)
R = stereoParams_pi1.RotationOfCamera2';
t = stereoParams_pi1.TranslationOfCamera2' / 1000;

% inverse transformation (cam1-to-cam2)
Rt = [R' -R'*t; 0 0 0 1];  % Rt = inv([R t; 0 0 0 1])

% point tranformation to camera frame
XYZ = cl1.Location';
XYZ(4,:) = 1;
xyz = Rt(1:3,:) * XYZ;

% point transformation to image plane
uv = A * xyz;
uv = bsxfun(@rdivide, uv(1:2,:), uv(3,:));

% assign depth (in meters)
uv(3,:) = xyz(3,:) * 1000;

% assign colors and create point cloud
RGB = uint8(impixel(scene2, uv(1,:), uv(2,:)));
pc = pointCloud(uv', 'Color',RGB);

% filter point cloud
roi = [0 size(scene2,2); 0 size(scene2,1); -Inf Inf];
pc = select(pc, findPointsInROI(pc, roi));

figure; pcshow(pc)
```

You could also use the function [`cv.projectPoint`](http://amroamroamro.github.io/mexopencv/matlab/cv.projectPoints.html) to project 3d points to image plane (it even takes into account the distortion coefficients).

**Comment by andriskuciks** [comment]
Thank you for your help Amro. But I still believe that I did it in the right way. If camera1 is the RGB camera and camrea2 is the ToF and I'm transforming the 3D point which I obtain from the ToF output (the pointcloud) to image plane then this equation `x1 = R*x2 + t` executes correctly, doesn't it? Because I tried to do the same code with different calibration results, when camera1 was the ToF and camera2 was the RGB and the results where off in x axis and mirrored (x axis flipped) compared to `scene2`. Thanks for the supported code. I will check it out, compare to my code and then come back with the results. 

Regards Andris

**Comment by amroamroamro** [comment]
I was also confused by which of the two is camera 1 and camera 2, which is why I asked.

If you still have the stereo calibration images of chessboards, try repeating the calibration, this time making sure to correctly assign cam1/cam2. Then you wont need to invert `[R t]`.
It would help if you'd share those images...

And just to make sure the math is clear, here's how we get the inverse transform:

```
x1 = R*x2 + t
x1 - t = R*x2
inv(R) * (x1 - t) = x2
R'*(x1 - t) = x2     # because R is orthogonal
R'*x1 - R'*t = x2

==> x2 = RR*x1 + tt, where RR = R' and tt = -R'*t
```

**Comment by amroamroamro** [comment]
It's because of the different conventions used, where a 2D/3D point is stored as either column or row vector.

Notice in [OpenCV docs](https://docs.opencv.org/master/d9/d0c/group__calib3d.html#details), the pinhole camera model is described by the equation:

    s * [u;v;1] = A * [R,t] * [X;Y;Z;1]

while in [MATLAB CVST docs](https://www.mathworks.com/help/vision/ug/camera-calibration.html) it is:

    w * [x y 1] = [X Y Z 1] * [R;t] * K

which explains why all of `R`, `t`, and `K` are transposed between the two, as it depends on how you do the multiplication:

    # for a matrix M and a vector v
    (M * v)' = v' * M'

In addition the distortion coefficients in CVST are separately stored as `[k1 k2 k3]` and `[p1 p2]` for radial and tangential coeffs respectively, while OpenCV represent it as one vector in this order `[k1 k2 p1 p2 k3 ...]` (the first five anyway, seeing that it supports more types of distortions).

Also notice that unlike MATLAB, the camera intrinsic matrix in OpenCV has no skew. The reason is that almost all modern cameras have no skew, so the OpenCV calibration functions assume it is zero and do not compute it (older versions of OpenCV < 2.0 might have had it, not sure).

**Comment by andriskuciks** [comment]
Okay, thats the reason of my confusion. 
Thanks for the great explenation and for your input in this problem I had! If I'll have any other problem with CV, I hope you don't mind if I would send you an e-mail straight away

**Comment by amroamroamro** [comment]
So I checked [online](https://stackoverflow.com/a/29079548/97160), and there's one part I have misinterpreted. In [`stereoParameters`](https://www.mathworks.com/help/vision/ref/stereoparameters.html) docs it says:

![stereoparameters](https://user-images.githubusercontent.com/83908/38989820-bec978dc-43e0-11e8-8158-af8ac0fc0a67.png)

It's a bit ambiguous, but I believe it means that `RotationOfCamera2` and `TranslationOfCamera2` describe the transformation from camera1's coordinates into camera2's coordinates, not the other way around like I said before..

So if you have a point `x1` in camera1 frame (as column vector `[X;Y;Z]`), `x2` coords in camera2 frame is given by:

    R = stereoParams.RotationOfCamera2';
    t = stereoParams.TranslationOfCamera2';
    x2 = R*x1 + t;    % NOT x1=R*x2+t !!

which agrees with the above results, and why you had to set the depth-cam as cam1 in the calibration, and also why you had to invert `[R t]` when depth-cam was set as cam2.

Fwiw, the same interpretation holds for OpenCV function [`cv::stereoCalibrate`](https://docs.opencv.org/master/d9/d0c/group__calib3d.html#ga91018d80e2a93ade37539f01e6f07de5) with its `R`,`T` output.

Sorry for adding to the confusion ;)

**Comment by amroamroamro** [comment]
And if you want to see if the math checks out, we start with:

    x2 = R*x1 + t

we know that `x1 = R1*x + t1` (where R1/t1 is the pose of cam1), so we get:

    x2 = R*(R1*x + t1) + t
    x2 = (R*R1)*x + (R*t1+t)

so:

    x2 = RR*x + tt
    where RR=R*R1 and tt=R*t1+t

similarly we know `x2 = R2*x + t2` (R2/t2 is the pose of cam2),
hence `R2 = R*R1` and `t2=R*t1+t`.

We can check this empirically from the calibration data:

```matlab
load('color_cloud.mat', 'stereoParams_pi1')

for i=1:10
    R1 = stereoParams_pi1.CameraParameters1.RotationMatrices(:,:,i)';
    R2 = stereoParams_pi1.CameraParameters2.RotationMatrices(:,:,i)';
    t1 = stereoParams_pi1.CameraParameters1.TranslationVectors(i,:)';
    t2 = stereoParams_pi1.CameraParameters2.TranslationVectors(i,:)';
    R = stereoParams_pi1.RotationOfCamera2';
    t = stereoParams_pi1.TranslationOfCamera2';

    norm((R*R1) - R2)
    norm((R*t1+t) - t2)
end
```

the difference should be close to zero in all pairs of images.

If you started out with `x1 = R*x2 + t` (wrong assumption!), you'll get incorrect values from the data.

**Comment by andriskuciks** [comment]
That was what I was trying to do before you fixed the code of the missalignment. Now it all makes sense and yes, now it all agrees to the code and the results we acquired.  
Just tested the supported theory of rotation matrices, and it all works out as you said it would!
Thanks for your support, this will help me massively wrinting my bachelor's thesis! 
Best of luck and keep up the sweet colaboration Amro!
Regards, Andris!

**Comment by andriskuciks** [comment]
​Hi @amroamroamro 
It's Andris from github, you helped me to do the depth scene mapping to image plane. Now I'm trying to find the minimum range at which the two scenes maps perfectly on each other. I started from 20cm distance up to 1.1m distance but it seems like the dispacement stays the same no matter what the distacnce is. Maybe you could help me understand where this misdisplacement comes from and how to fix that. Attached you will find the point clouds and color images from different distances as well as the code I used and the stereoParams variable. Camera1 in stereoParams  is the RGB camera. Hope you have time to look at this. Please respond as soon as possible either you have time to look at this problem or don't.
Best Regards,
Andris 
[Help.zip](https://github.com/kyamagu/mexopencv/files/1987726/Help.zip)

**Comment by andriskuciks** [comment]
Well if you try to run the code to get the color pointcloud and you can see that the color and depth still doesn't align perfectly. My assumption was if I increase the distance it should align perfectly at some pont, I believe 1m should be enough to align both scenes but it wasn't. And when I looked at the resulting point cloud, it looked like the different scenes didn't even get closer to each other when I increased the distance. I hope you understand what I was trying to say

**Comment by amroamroamro** [comment]
honestly, I don't see it.

**Comment by andriskuciks** [comment]
![image](https://user-images.githubusercontent.com/35566880/39983926-10dabd18-5762-11e8-8673-61b938220342.png)
Like in this resulting point cloud. If you move the point cloud arround and look at the Raspberry Pi box, you can see, tht the top of the box in point cloud doesnt match perfectly the color image. This example is from 20 cm scene, but you can see it in 50 cm scene as well and 1m away, it is hard to see but the two scenes still don't align perfectly

**Comment by amroamroamro** [comment]
Don't know, could be due to poor stereo calibration... Try repeating the calibration process while using more chessboard images in varying poses, and see if it improves the result. Your cameras are of small resolution, so maybe go up to 20 image pairs.

There's this paragraph in [MATLAB docs](https://www.mathworks.com/help/vision/ug/stereo-camera-calibrator-app.html#buejbxy-12) about improving calibration:

> To improve the calibration, you can remove high-error image pairs, add more image pairs, or modify the calibrator settings.
> 
> Consider adding more images if:
> 
> - You have less than 10 images.
> - The patterns do not cover enough of the image frame.
> - The patterns do not have enough variation in orientation with respect to the camera.
> 
> Consider removing images if the images:
> 
> - The images have a high mean reprojection error.
> - The images are blurry.
> - The images contain a checkerboard at an angle greater than 45 degrees relative to the camera plane.
> - The images contain incorrectly detected checkerboard points.

Now I don't know much about ToF cameras, but I think depth estimating tends to suffer if objects are too close to camera (or too far).

Also it would help the comparison if you do the same scene from various distances (i.e keep objects fixed while moving camera further away 20/50/80/100cm). I saw in the images you attached above that the box and pen marker are moved around, this makes it harder to compare the quality of alignment across images. Just a though..

**Comment by andriskuciks** [comment]
When I did the calibration, I used 30 images from each camera at different angles and distances... I could send to you the calibration images but I don't think it would be any help. I'll redo the scenes, trying to keep the objects fixed and move only the stereo system but there is no guarantee that the angle will be the same in all distances. I'll try my best and load the results here.
Another reason I thought that may cause this, is that in calibration I used amplitude images from ToF instead of point clouds and that may cause the scenes not to align correctly but I'm not sure. 

About the ToF. Estimating the depth is suffering if the objects are further than the unumbigious distance, then ToF believes the objects are a lot closer than they actually are. In close distance's from my ToF experiance , the depth is suffering only when the IR light reflects too much from the scene and in the resulting point cloud you can see saturation. When I got the point clouds from the scene, it wasn't further than the unumbigious distance and when the scene was 20 cm away, there wasn't any saturation, so I believe that this wouldn't be the case of error

**Comment by andriskuciks** [comment]
So I tried to keep the scene fixed and move only the system arround. The problem was that the system has a lot of wires connected and its hard to keep it un the same angle and in straight line, when moving arround. Now it seem like that the scene is aligning better when the disance is increasing. At least I saw a big difference between 20 and 50 cm distance. Maybe at 80 cm scene alignes perfectly, but it is hard to see as less pixels reflects form the objects un in the resulting images they are really small. I will try to find  some bigger object and try it again. Attached are the scenery images when the objects are fixed
[depth color scene.zip](https://github.com/kyamagu/mexopencv/files/2012885/depth.color.scene.zip)

**Comment by amroamroamro** [comment]
You certainly know more about ToF cameras than I do. I've never worked with one!

Now remember that stereo calibration functions in MATLAB and OpenCV are meant for regular color cameras (i.e two RGB cams). Your setup instead uses amplitude images from ToF cam for one..

 [Searching online](https://www.google.com/search?q=time-of-flight+camera+calibration), you can find a number of papers (some with code) proposing specialized calibration methods specifically involving ToF cameras, that claim better results than a generic color camera calibration. You could look into that.

Other than this, I'm not sure I could be of more help here, good luck :)
