### ISSUE TITLE
Pose Estimation Error

### ISSUE THREAD

**Issue by alina33** [kyamagu/mexopencv#407]
I was testing mexopencv functions for estimating pose for an image pair from MATLAB's Visual Odometry Example. However, the result of relative location computed by mexopencv functions is different (negative sign of 3rd element of the Location Vector) from the ground-truth.
Moreover, the results computed from MATLAB's Functions are matching with the ground-truth.

I has been observed that this discrepancy is generated when there is a forward movement in the camera (for viewId = 15), however results are good for other images (viewId = 2,3,4 etc.).

Why is it so? Both results are provided below.

### Results:

```
groundTruth_Loc = -2.191584000000000  -0.018982000000000  26.857834000000000

relativeLoc_normalized = -0.065220918814029  -0.049103970994921  26.946984672662680 % MATLAB's Result

relativeLoc_normalized = 2.487593988338816  3.514638449996284  -26.600861652057898 % MEXOPENCV's Result
```

**Comment by tobycollins** [comment]
Hello, you are aware that relative pose cannot be computed uniquely?
Specifically that translation is comptable up to an unknown scale factor?
This is because you cannot know if the camera is closer to the scene and
moving slower, or further to the scene and moving faster. The translation
direction (computed by diving translation by its norm) can be computed
uniquely and that's what you should be comparing with ground truth.

Hope this helps,

Toby

**Comment by alina33** [comment]
@tobycollins yes I am aware of that. If you look into the code, you will see that I am normalizing the estimated relative translation with respect to the ground truth translation.

However, results from MATLAB and MEXOPENCV are different, why is it so? They must be precise. Why are not they?

**Comment by tobycollins** [comment]
You can be getting inconsistent results if your data is close to
degenerate. For example if your scene is far compared to the amount of
translation. When a scene is close to being degenerate then some noise in
the correspondences can produce large differences in the results. Also if
your scene is close to planar you have a degeneracy because you cannot
estimate the essential matrix reliably. If I were you I would double check
results using synthetic data and zero noise and a non degenerate scene.
This make sure you are using the libs correctly. If that succeeds then the
problem lies with your data.

**Comment by alina33** [comment]
But MATLAB's functions are providing good result for the same data...
Problem is with the results of MEXOPENCV's functions...
Could you please run these codes once? It will provide you insight about the subject issue...

**Comment by alina33** [comment]
If there is any issue with the data then MATLAB's functions would not be giving good results.

**Comment by tobycollins** [comment]
The way you are computing feature matches is not identical (MATLAB with
surf and upright descriptors, OpenCV with SIFT). These match sets are going
to be different and consequently the relative poses are going to be
different. The big difference could be xplained by SIFT not producing
enough correct matches.

**Comment by alina33** [comment]
Could even just a slight difference in feature matches yield wrong essential matrix.....?
