### ISSUE TITLE
Building 64 bit OpenCV with mingw from Octave 4.4.0

### ISSUE THREAD

**Issue by AvinoamK** [kyamagu/mexopencv#409]
How do I build 64 bit OpenCV with mingw from Octave 4.4.0?

Thanks

**Comment by amroamroamro** [comment]
The instructions in the wiki describe the 32-bit case:
https://github.com/kyamagu/mexopencv/wiki/Installation-%28Windows%2C-Octave%2C-OpenCV-3%29

Just adapt them to 64-bit, the steps should be quite similar.
In fact almost no change except getting the x64 octave version instead of the x86 version, plus some minor path adjustments.

Try it, and let us know if you have any build problems.

**Comment by amroamroamro** [comment]
As part of CI testing mexopencv, I did in fact build both 32/64 bits versions of OpenCV using mingw.

You can see the AppVeyor build script in my branch:
https://github.com/amroamroamro/opencv/blob/tag_3.4.0/appveyor.yml

Here's the build log:
https://ci.appveyor.com/project/amroamroamro/opencv/build/3.4.0.27

And the binaries produced:
https://github.com/amroamroamro/opencv/releases

Note that the last build (opencv 3.4.0) was using Octave 4.2.1 (before 4.4.0 was out).
I'll be updating the CI tests to use the latest octave with the next mexopencv release.
I don't think there should be any major problem regarding the new octave.

**Comment by AvinoamK** [comment]
Thanks for the explanation.
I've tried to build opencv 3.4.0 with Octave 4.4.0 64 bit, but it failed.

**Comment by AvinoamK** [comment]
The failure is in videoio/src/cap.cpp
maybe this is related to the mingw patch?

**Comment by AvinoamK** [comment]
Thanks.
Addition of `-DENABLE_PRECOMPILED_HEADERS=OFF` fixed the problem
Maybe this should added to the wiki.
