### ISSUE TITLE
Remove Duplicate Keypoints not working

### ISSUE THREAD

**Issue by youthiya** [kyamagu/mexopencv#422]
Hello. I am working on removal of duplicate keypoints after SIFT feature detection but following function is not removing the duplicate keypoints (that have same coordinates but different orientation).

`keypoints = cv.KeyPointsFilter.removeDuplicated(keypoints)`

Is this function coded wrong? What could be the issue?

**Comment by amroamroamro** [comment]
A keypoint struct has the [following][1] fields:
- `pt`
- `size`
- `angle`
- `response`
- `octave`
- `class_id`

Looking at the opencv source code of the `removeDuplicated` function (see [here][2]), two keypoints are considered duplicate if they have the same `pt`, `size`, and `angle` (all three fields):

```matlab
img = imread('image.jpg');
obj = cv.SIFT();
kpts = obj.detect(img);

kpts0 = cv.KeyPointsFilter.removeDuplicated(kpts);
```

If you want to consider only `pt` (coordinates) when removing duplicates, you'll have to filter the points yourself. You can do this in plain MATLAB:

```matlab
pt = cat(1, kpts.pt);
[~,ind] = unique(pt, 'rows');
kpts1 = kpts(ind);
```

You can make this fancier by using [`uniquetol`][3] instead of [`unique`][4] to perform comparison with a tolerance instead of an exact comparison (i.e. keep points that are at least a distance tolerance apart, not necessarily exactly equal):

```matlab
pt = cat(1, kpts.pt);
tol = 0.1;
[~,ind] = uniquetol(pt, tol, 'ByRows',true, 'DataScale',[1 1]);
kpts2 = kpts(ind);
```

[1]: http://amroamroamro.github.io/mexopencv/matlab/cv.KeyPointsFilter.html
[2]: https://github.com/opencv/opencv/blob/3.4.1/modules/features2d/src/keypoint.cpp#L194-L224
[3]: https://www.mathworks.com/help/matlab/ref/uniquetol.html
[4]: https://www.mathworks.com/help/matlab/ref/unique.html

**Comment by youthiya** [comment]
Thanks a lot. Issue is clear now.

**Comment by youthiya** [comment]
Thanks a lot. Issue is clear now.
