### ISSUE TITLE
Undefined function or variable 'LSDDetector_'.

### ISSUE THREAD

**Issue by Dzhange** [kyamagu/mexopencv#435]
when I successfully built mexopencv on my Mac, I got this error 
```
Undefined` function or variable 'LSDDetector_'.

Error in cv.LSDDetector (line 48)
            this.id = LSDDetector_(0, 'new');
```

when I run 
```
a = cv.LSDDetector()
```

I think maybe somehow I failed to biuld mexopencv with opencv_contrib.
also, I'm building with opencv3.4.3, which is default on homebrew, does it matter?
Is there any solution?

**Comment by Dzhange** [comment]
Well, I read the Makefile and found that I have to add "contirb" at the end of the command.
I think you should include this in the Readme.

**Comment by amroamroamro** [comment]
Hi. I believe we do mention the "contrib" target in the README file, it's listed under Linux section though (macOS and Linux instructions are really the same, except for package managers):

> To enable support for contributed modules, you must build OpenCV from both opencv and opencv_contrib sources. You can then compile mexopencv as:
>
>     $ make all contrib

As to the version, yes I suggest using the supported version (v3.4.1 currently), otherwise you might get compile errors. I'm working on updating to the latest releases.
